### ISSUE TITLE
Rating shows as rating - 0.5 if AllowHalfRating is false

### ISSUE THREAD

**Issue by cbenhagen** [sarbagyastha/flutter_rating_bar#7]
<img width="195" alt="Screenshot 2019-07-04 at 13 07 27" src="https://user-images.githubusercontent.com/814785/60662451-b3121f80-9e5c-11e9-89df-222414665215.png">

```dart
FlutterRatingBar(
    initialRating: 3,
    allowHalfRating: false,
    onRatingUpdate: (rating) {
        print(rating);
    },
)
```

**Comment by sarbagyastha** [comment]
The issue is already fixed. Will update the package tomorrow. Thank you!

**Comment by cbenhagen** [comment]
Thank you for the quick response. Where is this fixed? The latest version from github still shows this issue:

```yaml
  flutter_rating_bar:
    git:
      url: https://github.com/sarbagyastha/flutter_rating_bar.git
```
