### ISSUE TITLE
disable onTap, allow only onDrag

### ISSUE THREAD

**Issue by FatahZullDev** [sarbagyastha/flutter_rating_bar#87]
hello sir. appreciate if you can help me how to disable onTap function, I want only onDrag. 
Because when I touch the first star to drag, suddenly onTap triggered

**Comment by ikicodedev** [comment]
I created a PR with a simple fix -> https://github.com/sarbagyastha/flutter_rating_bar/pull/98
You can use 

```
flutter_rating_bar:
    git:
      url: https://github.com/ikicodedev/flutter_rating_bar
      ref: master
```
